### ISSUE TITLE
Leak reporting truncation issues with many handles open before test

### ISSUE THREAD

**Issue by tadman** [socketry/rspec-files#3]
If in the course of testing you have a number of handles open before the test that are expected to be there, then the output can be truncated by the RSpec formatter and it makes understanding the source of the new handles more difficult than it needs to be.

Since the real issue here is handles being left open, not *what* is open, it may make sense to redefine the [leak assertion](https://github.com/socketry/rspec-files/blob/master/lib/rspec/files/leaks.rb) as:

    expect(after_ios - before_ios).to eq([ ])

Where this communicates that you're expecting an empty array, and if there's anything new showing up then it'll make that array non-empty, but also, importantly, won't be truncated unless you've created a *lot* of new IO handles. If that's the case you've got at least a few you can investigate.

**Comment by ioquatix** [comment]
Good idea, can you make a PR?

**Comment by tadman** [comment]
Let me look into that, sure.

**Comment by tadman** [comment]
How do you write an RSpec test for an RSpec test wrapper?

**Comment by ioquatix** [comment]
I think my code might have some examples of how to do this already... let me check.

**Comment by ioquatix** [comment]
I was thinking of this, but it's not what we wanted:

https://github.com/socketry/rspec-memory/blob/master/spec/rspec/memory_spec.rb#L73-L79

I have seen this before somewhere.

**Comment by tadman** [comment]
It looks like the use of `IO.pipe` to create arbitrary handles in the leak testing complicates things because RSpec, for reasons I'm still trying to understand, goes ahead and tries to [read data from any handles when reporting a diff on IO objects](https://github.com/rspec/rspec-expectations/blob/e7cab36a0194878cf19f2c9cd0f41faf1a62b774/lib/rspec/matchers/composable.rb#L147).

This results in a jam where, of course, nothing is ever coming out of that pipe so RSpec waits forever.

**Comment by ioquatix** [comment]
Oh no....! On the face of it, that is kind of weird.

**Comment by tadman** [comment]
Consolidated this into a [pull request](https://github.com/socketry/rspec-files/pull/4).

**Comment by ioquatix** [comment]
Thanks 😊
